spring:
  application:
    name: "api-abn-recipe"

server:
  servlet:
    context-path: /api

management:
  endpoint:
    info:
      enabled: true
  endpoints:
    web:
      base-path: /management
      exposure:
        include: health,info,loggers

database:
  mongodb:
    name: recipes
    url: mongodb://localhost:27017/